version: 0.0

os: linux

files:
  - source: /
    destination: /tmp

hooks:
  ApplicationStop:
    - location: stop-process.sh
      timeout: 80
      runas: ec2-user
  ApplicationStart:
    - location: start-process.sh
      timeout: 80
      runas: ec2-user
