version: 0.0

os: linux

files:
  - source: /airline.war
    destination: /tmp
    
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 300
      runas: root
